export default {
  products: [
    {
      id: 1,
      name: "Nike T-Shirt",
      price: 65,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 2,
      name: "Nike T-Shirt 70",
      price: 70,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 3,
      name: "T-Shirt",
      price: 80,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 4,
      name: "T-Shirt",
      price: 85,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 5,
      name: "T-Shirt",
      price: 50,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 6,
      name: "T-Shirt",
      price: 40,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 7,
      name: "T-Shirt",
      price: 47,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
    {
      id: 8,
      name: "T-Shirt",
      price: 100,
      brand: "Nike",
      category: "T-Shirts",
      rating: 4.3,
      numrating: 46,
      image: "/images/amazon.jpg",
      countInStock: 6,
    },
  ],
};
